#ifndef UMCA_ERROR_H
#define UMCA_ERROR_H

enum umca_error
{
  UMCA_OK = 0,
  UMCA_ERR_INVALID_ARG = -1,
  UMCA_ERR_BAD_MAGIC = -2,
  UMCA_ERR_UNSUPPORTED_VERSION = -3,
  UMCA_ERR_BAD_HEADER = -4,
  UMCA_ERR_PAYLOAD_TOO_LARGE = -5,
  UMCA_ERR_LENGTH_MISMATCH = -6,
  UMCA_ERR_CRC = -7,
  UMCA_ERR_UNSUPPORTED_TYPE = -8,
  UMCA_ERR_CAPACITY = -9,
  UMCA_ERR_TOPIC_COLLISION = -10,
  UMCA_ERR_DUPLICATE = -11,
  UMCA_ERR_STALE = -12,
  UMCA_ERR_NOT_FOUND = -13,
  UMCA_ERR_TIMEOUT = -14,
  UMCA_ERR_PHY = -15,
  UMCA_ERR_UNSUPPORTED_FLAGS = -16,
  UMCA_ERR_UNSUPPORTED_QOS = -17,
  UMCA_ERR_BAD_PAYLOAD = -18,
  UMCA_ERR_BAD_STATE = -19
};

#endif
